changelog:
  exclude:
    labels:
      - ts-proj
    authors:
      - octocat

  categories:
    - title: Major
      labels:
        - Semver-Major

    - title: Minor
      labels:
        - Semver-Minor

    - title: Patch
      labels:
        - Semver-Patch
