name: "Pull Request"

on:
  push:
    tags:
      - ts-v*

permissions:
  contents: write

jobs:
  do-thing:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4

      - # Testing Generating Release Notes
        id: update-status-check
        name: Update Status Check
        uses: actions/github-script@v7
        with:
          script: |
            if (context.ref === undefined) {
              return;
            }

            const tagName = context.ref.replace("refs/tags/", "");
            const result = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              configuration_file_path: '.github/release-config.yml'
            });

            console.log(JSON.stringify(result, null, 2));
