name: "Pull Request"

on:
  push:
    tags:
      - ts-v*

permissions:
  contents: write

jobs:
  do-thing:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4

      - # Testing Generating Release Notes
        id: update-status-check
        name: Update Status Check
        uses: actions/github-script@v7
        with:
          script: |
            if (context.ref === undefined) {
              return;
            }

            const tagName = context.ref.replace("refs/tags/", "");

            const result = await github.rest.repos.generateReleaseNotes({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              configuration_file_path: '.github/release-config.yml'
            });

            if (result.data === undefined) {
              console.error(result)
              throw new Error('No data on body')
            }

            const title = result.data.name;
            const body = result.data.body;

            const createReleaseResult = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: tagName,
              name: title,
              body: body,
            });

            console.log(createReleaseResult)
