name: Testing edited release events

on:
  release:
    types: [edited]

jobs:
  test-release-action:
    runs-on: ubuntu-latest
    steps:
      -
        id: log-type
        name: Log Type
        run: |
          echo "Event: ${{ github.event.action }}"

      -
        id: validate-release
        name: Update Prerelease 
        uses: actions/github-script@v7
        with:
          script: |
            const re = /^(?<lang>\w*)-sdk-v(?<version>\d+\.\d+\.\d+)$/ 
            const releaseName = process.env.RELEASE_NAME ?? '';
            const match = releaseName.match(re);

            if (match === null) {
              core.setFailed(`Invalid release name: ${releaseName}`);
              return;
            }

            console.log('Found match groups', match.groups)

            return match.groups;

      -
        id: test-output
        name: Testing JS Output
        run: |
          echo ${{ steps.validate-release.outputs.results.lang }}
          echo ${{ steps.validate-release.outputs.results.version }}
