name: "Pull Request"

on:
  pull_request:
    branches:
      - main
    type: ["open", "synchronize", "reopen"]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
