name: Publish Release Package

on:
  # @see https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
  release:
    types: [released]

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  validate-release:
    name: Validate Release
    runs-on: ubuntu-latest
    outputs:
      language: ${{ steps.validate-release.outputs.lang }}
      version: ${{ steps.validate-release.outputs.version }}
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      -
        id: log-type
        name: Log Type
        run: |
          echo "Event: ${{ github.event.action }}"

      -
        id: validate-release
        name: Update Prerelease 
        uses: actions/github-script@v7
        env:
          RELEASE_NAME: ${{ github.event.release.name }}
        with:
          script: |
            const script = require('./.github/scripts/validate-release.js');
            await script({ github, context, core });

  kotlin-publish:
    name: Publish Kotlin Package
    runs-on: ubuntu-latest
    needs: validate-release
    if: needs.validate-release.outputs.language == 'kotlin'
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4

      -
        id: configure-git
        name: Configure git
        run: |
          # TODO: USE BWELL USER
          # git config user.name "bwell-dev"
          # git config user.email "bwell-dev@icanbwell.com"
          git config user.name "Cole Voss"
          git config user.email "voss.cole@gmail.com"

          # Need to checkout main since actions/checkout starts at detached HEAD
          git checkout main

      -
        id: tag-current-commit
        name: Tag Current Commit
        env:
          NEW_TAG: ${{ github.event.release.name }}
          VERSION: ${{ needs.validate-release.outputs.version }}
        # TODO:
        # The tagging would also be done by npm in the typescript version.
        run: |
          # TODO: This should be updated to correct dir
          cd ./kotlin-proj
          npm version $VERSION --git-tag-version=false

          # npm publish

          git status --porcelain

          git add -A
          # I believe this won't trigger a workflow run since its ran in a workflow
          # but its probably best to add [no ci] anyway
          git commit -m "[no ci] Kotlin SDK Release $VERSION" --no-verify

          git tag -a $NEW_TAG -m "$NEW_TAG Publish Release"
          git push origin main --follow-tags

          echo "New Tag Created for Kotlin Release: $NEW_TAG" >> $GITHUB_STEP_SUMMARY

  typescript-publish:
    name: Publish TypeScript Package
    runs-on: ubuntu-latest
    needs: validate-release
    if: needs.validate-release.outputs.language == 'typescript'
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4

      -
        id: configure-git
        name: Configure git
        run: |
          # TODO: USE BWELL USER
          # git config user.name "bwell-dev"
          # git config user.email "bwell-dev@icanbwell.com"
          git config user.name "Cole Voss"
          git config user.email "voss.cole@gmail.com"

          # Need to checkout main since actions/checkout starts at detached HEAD
          git checkout main

      -
        id: tag-current-commit
        name: Tag Current Commit
        env:
          NEW_TAG: ${{ github.event.release.name }}
          VERSION: ${{ needs.validate-release.outputs.version }}
        run: |
          # TODO: This should be updated to correct dir
          cd ./ts-proj
          npm version $VERSION --git-tag-version=false

          # TODO: On publish make sure to use --tag <not latest>
          # @see https://docs.npmjs.com/cli/v9/commands/npm-dist-tag
          # What do we want the tag to be?
          # npm publish --tag=next

          # Logs changed files in the following format to confirm the changes were made
          # ?? path/to/changed/file.json
          git status --porcelain

          git add -A

          # I believe this won't trigger a workflow run since its ran in a workflow
          # but its probably best to add [no ci] anyway
          git commit -m "[no ci] Typescript SDK Release $VERSION" --no-verify

          git tag -a $NEW_TAG -m "$NEW_TAG Publish Release"
          git push origin main --follow-tags

          echo "New Tag Created for TypeScript Release: $NEW_TAG" >> $GITHUB_STEP_SUMMARY

  re-tag-release:
    name: Retag Github Release
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [validate-release, kotlin-publish, typescript-publish]
    steps:
      # Checkout
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        id: previous-release-tag
        name: Generate Tag
        env:
          LANGUAGE: ${{ needs.validate-release.outputs.language }}
        run: |
          # Get the most recent non-rc release for the the published package
          # This is used for generating the changelog from the previous version
          # to the newly published version
          PREV_RELEASE_TAG=$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname)' | grep -E "$LANGUAGE-sdk-v.*" | grep -v 'rc' | head -n 2 | tail -n 1)
          echo "PREV_RELEASE_TAG=$PREV_RELEASE_TAG" >> "$GITHUB_OUTPUT"

      -
        id: validate-release
        name: Update Prerelease 
        uses: actions/github-script@v7
        env:
          RELEASE_ID: ${{ github.event.release.id }}
          NEW_TAG: ${{ github.event.release.name }}
          PREV_RELEASE_TAG: ${{ steps.previous-release-tag.outputs.PREV_RELEASE_TAG }}
          RELEASE_CONFIG: .github/${{ needs.validate-release.outputs.language }}-release-config.yml
        with:
          script: |
            const script = require('./.github/scripts/retag-release.js');
            await script({ github, context, core });
