name: Testing release events

on:
  release:
    types: [prereleased, released, edited]

jobs:
  test-release-action:
    runs-on: ubuntu-latest
    steps:
      -
        id: log-type
        name: Log Type
        run: |
          echo "Event: ${{ github.event.action }}"
